openapi: 3.0.3
info:
  title: RFID-BACK API
  version: 1.0.0
  description: API de gestion des cueilleurs, tags, activités et conformités

servers:
  - url: http://localhost:8080/api
    description: Serveur local de développement
  - url: https://api.apolog.fr/api
    description: Serveur de production

# -----------------------------------------------------------------------------------------------
# Endpoints section
# -----------------------------------------------------------------------------------------------
paths:
  # -----------------------------------------------------------------------------------------------
  # Reader section
  # -----------------------------------------------------------------------------------------------
  /readers:
    get:
      summary: List all readers
      operationId: listReaders
      tags: [Reader]
      responses:
        "200":
          description: Readers list
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ReadersList"
        "500": { $ref: "#/components/responses/InternalError" }
    post:
      summary: Create a new reader
      operationId: createReader
      tags: [Reader]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateReader"
      responses:
        "201":
          description: Reader
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Reader"
        "400": { $ref: "#/components/responses/InvalidRequest" }
        "500": { $ref: "#/components/responses/InternalError" }

  # -----------------------------------------------------------------------------------------------
  # Picker section
  # -----------------------------------------------------------------------------------------------
  /pickers:
    get:
      summary: List pickers with pagination
      description: |
        Get the sorted and filtered list of pickers with pagination support
      operationId: getPickers
      tags: [Picker]
      parameters:
        - $ref: "#/components/parameters/PageNumber"
        - $ref: "#/components/parameters/PageSize"
        - $ref: "#/components/parameters/PageSort"
      responses:
        "200":
          description: Pickers page
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PickersPage"
        "4XX": { $ref: "#/components/responses/InvalidRequest" }
        "500": { $ref: "#/components/responses/InternalError" }
    post:
      summary: Create a picker
      description: Create a new picker
      operationId: createPicker
      tags: [Picker]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreatePicker"
      responses:
        "201":
          description: Created picker
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Picker"
        "400": { $ref: "#/components/responses/InvalidRequest" }
        "409": { $ref: "#/components/responses/AlreadyExist" }
        "500": { $ref: "#/components/responses/InternalError" }

  /pickers/{pickerId}:
    parameters:
      - in: path
        name: pickerId
        required: true
        description: Identifiant du cueilleur
        schema:
          type: string
          format: uuid
    get:
      summary: Get picker detail
      description: Get detailed information about a specific picker
      operationId: getPicker
      tags: [Picker]
      responses:
        "200":
          description: Cueilleur
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Picker"
        "404": { $ref: "#/components/responses/NotFound" }
        "500": { $ref: "#/components/responses/InternalError" }
    put:
      summary: Update picker
      operationId: updatePicker
      tags: [Picker]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdatePicker"
      responses:
        "200":
          description: Cueilleur mis à jour
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Picker"
        "400": { $ref: "#/components/responses/InvalidRequest" }
        "404": { $ref: "#/components/responses/NotFound" }
        "409": { $ref: "#/components/responses/AlreadyExist" }
        "500": { $ref: "#/components/responses/InternalError" }
    delete:
      summary: Delete picker
      operationId: deletePicker
      tags: [Picker]
      responses:
        "204":
          description: Cueilleur supprimé
        "404": { $ref: "#/components/responses/NotFound" }
        "409": { $ref: "#/components/responses/AlreadyExist" }
        "500": { $ref: "#/components/responses/InternalError" }

  # -----------------------------------------------------------------------------------------------
  # Tag section
  # -----------------------------------------------------------------------------------------------
  /tags/buckets/{bucketNumber}:
    post:
      summary: Register tags for a bucket
      description: >
        Register a list of tags for a specific bucket number. Existing associations
        with this bucket are cleared before registering the provided tags.
      operationId: registerTagsForBucket
      tags: [Tag]
      parameters:
        - in: path
          name: bucketNumber
          required: true
          description: Bucket number to associate with the provided tags
          schema:
            type: integer
            minimum: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterTagsRequest"
      responses:
        "200":
          description: Tags registered for the bucket
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterTagsResponse"
        "400": { $ref: "#/components/responses/InvalidRequest" }
        "500": { $ref: "#/components/responses/InternalError" }

  /tags/scan:
    post:
      summary: Scan a tag and report its compliance state
      description: >
        Endpoint called by an RFID reader to report whether a scanned tag is compliant.
        Accessible only with the API token generated during reader registration.
      operationId: scanTag
      tags: [Tag]
      security:
        - ReaderApiToken: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ScanTagRequest"
      responses:
        "200":
          description: |
            Tag scanned successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ScanTagResponse"
        "400": { $ref: "#/components/responses/InvalidRequest" }
        "401": { $ref: "#/components/responses/Unauthorized" }
        "500": { $ref: "#/components/responses/InternalError" }

# ---------------------------------------------------------------------------
# COMMON DEFINITONS
# ---------------------------------------------------------------------------
components:
  # ---------------------------------------------------------------------------
  responses:
    Done:
      description: Retourné lorsque l'action demandée a été réalisée
    Created:
      description: Retourné lorsqu'une nouvelle ressource a été créée
    Modified:
      description: Retourné lorsqu'une ressource a été modifiée
    Deleted:
      description: Retourné lorsqu'une ressource a été supprimée
    AlreadyExist:
      description: Retourné lorsqu'une ressource existe déjà
    NotFound:
      description: Retourné lorsqu'une ressource est introuvable
    InvalidRequest:
      description: Requête invalide
    InternalError:
      description: Erreur interne côté serveur
    UnexpectedError:
      description: Retourné lorsqu'une nouvelle ressource a été créée
    Unauthorized:
      description: Jeton API manquant ou invalide

  # ---------------------------------------------------------------------------
  parameters:
    PageNumber:
      name: page
      in: query
      description: Page number to retrieve (0-based)
      schema:
        type: integer
        minimum: 0
        default: 0
    PageSize:
      name: size
      in: query
      description: Elements per page
      schema:
        type: integer
        minimum: 1
        maximum: 100
        default: 20
    PageSort:
      name: sort
      in: query
      description: |
        Filtering and sorting criteria. Format: `field1,asc|desc`.
        example: : `lastname,asc`.
      schema:
        type: string
      example: lastname,asc

  # ---------------------------------------------------------------------------
  schemas:
    CreateReader:
      type: object
      properties:
        uid:
          type: string
          description: Reader uid
          example: Reader 1
      required:
        - uid

    Reader:
      allOf:
        - $ref: "#/components/schemas/CreateReader"
        - type: object
          properties:
            apitoken:
              type: string
              description: API token used by the reader to authenticate requests
              example: abcd1234efgh5678ijkl9012mnop3456
            creationDate:
              type: string
              format: date-time
              description: Reader creation date
              example: "2024-01-01T12:00:00Z"
            updateDate:
              type: string
              format: date-time
              description: Last update date of the reader
              example: "2024-01-02T12:00:00Z"
          required:
            - apitoken

    ReadersList:
      type: object
      properties:
        readers:
          type: array
          items:
            $ref: "#/components/schemas/Reader"
      required:
        - readers

    CreatePicker:
      type: object
      properties:
        lastname:
          type: string
          description: Picker last name
          example: Dupont
          maxLength: 50
        firstname:
          type: string
          description: Picker first name
          example: Alice
          maxLength: 50
        comment:
          type: string
          description: Additional comment about the picker
          example: Available only on weekends
          maxLength: 280
      required:
        - lastname
        - firstname

    UpdatePicker:
      allOf:
        - $ref: "#/components/schemas/CreatePicker"

    Picker:
      allOf:
        - $ref: "#/components/schemas/CreatePicker"
        - type: object
          properties:
            id:
              type: string
              format: uuid
              description: Picker unique identifier
            creationDate:
              type: string
              format: date-time
              description: Picker creation date
              example: "2024-01-10T15:00:00Z"
          required:
            - id
            - creationDate

    PageMetadata:
      type: object
      properties:
        page:
          type: integer
          description: Current page number
        size:
          type: integer
          description: Page size
        totalElements:
          type: integer
          description: Total number of elements
        totalPages:
          type: integer
          description: Total number of pages
        hasNext:
          type: boolean
          description: Tell if a next page exists
        hasPrevious:
          type: boolean
          description: Tell if a previous page exists
      required:
        - page
        - size
        - totalElements
        - totalPages
        - hasNext
        - hasPrevious

    PickersPage:
      type: object
      properties:
        content:
          type: array
          items:
            $ref: "#/components/schemas/Picker"
        metadata:
          $ref: "#/components/schemas/PageMetadata"
      required:
        - content
        - metadata

    ScanTagRequest:
      type: object
      properties:
        uid:
          type: string
          description: Unique identifier of the scanned tag
          example: E2000017221101891400A23G
        isCompliant:
          type: boolean
          description: Tells whether the scanned tag is compliant
          example: false
      required:
        - uid
        - isCompliant

    ScanTagResponse:
      type: object
      properties:
        uid:
          type: string
          description: Unique identifier of the scanned tag
          example: E2000017221101891400A23G
        isCompliant:
          type: boolean
          description: Tells whether the scanned tag is compliant
          example: false
        processedAt:
          type: string
          format: date-time
          description: Scan processing date and time
          example: "2024-01-15T09:30:00Z"
        message:
          type: string
          description: Compliance processing message
          example: Tag marked as non-compliant due to missing validation
      required:
        - uid
        - isCompliant
        - processedAt

    RegisterTagsRequest:
      type: object
      properties:
        uids:
          type: array
          description: Unique IDs of scanned tags
          minItems: 1
          items:
            type: string
            minLength: 1
            example: E2000017221101891400A23G
      required:
        - uids

    RegisterTagsResponse:
      type: object
      properties:
        bucketNumber:
          type: integer
          description: Bucket number associated with the registered tags
          example: 12
        registeredCount:
          type: integer
          description: Number of tags now associated with the bucket
          example: 42
      required:
        - bucketNumber
        - registeredCount

  # ---------------------------------------------------------------------------
  securitySchemes:
    ReaderApiToken:
      type: apiKey
      in: header
      name: x-api-token
      description: API token assigned to the reader during its registration
