/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.6.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.rfidback.generated.api;

import com.rfidback.generated.model.TagDto;
import com.rfidback.generated.model.TagScanRequest;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import javax.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-10-28T15:54:57.979750+01:00[Europe/Paris]", comments = "Generator version: 7.6.0")
@Validated
@Tag(name = "Tag", description = "the Tag API")
public interface TagApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /api/tags/scan : Enregistre une lecture de tag RFID
     *
     * @param xApiToken  (required)
     * @param tagScanRequest  (required)
     * @return Tag compté avec succès (status code 200)
     */
    @Operation(
        operationId = "registerScan",
        summary = "Enregistre une lecture de tag RFID",
        tags = { "Tag" },
        responses = {
            @ApiResponse(responseCode = "200", description = "Tag compté avec succès", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TagDto.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/api/tags/scan",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<TagDto> _registerScan(
        @NotNull @Parameter(name = "x-api-token", description = "", required = true, in = ParameterIn.HEADER) @RequestHeader(value = "x-api-token", required = true) String xApiToken,
        @Parameter(name = "TagScanRequest", description = "", required = true) @Valid @RequestBody TagScanRequest tagScanRequest
    ) {
        return registerScan(xApiToken, tagScanRequest);
    }

    // Override this method
    default  ResponseEntity<TagDto> registerScan(String xApiToken, TagScanRequest tagScanRequest) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"uid\" : \"uid\", \"conforme\" : true, \"dateComptage\" : \"2000-01-23T04:56:07.000+00:00\", \"status\" : \"PENDING\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
