@startuml TAG_LIFECYCLE
title Cycle de vie des Tags

[*] --> IDLE : Enregistrement
IDLE --> IDLE : Affectation
IDLE --> EnAttente : Démarrage de l'activité liée
EnAttente --> Comptabilisé : Lecture pendant l'activité 
Comptabilisé --> [*] : Suppression du système
IDLE : Le Tag est enregistré dans le système
EnAttente : Le Tag est affecté à une activité en cours
Comptabilisé : Le Tag a été lu dans l'activité en cours

@enduml