@startuml

' configuration
hide circle
' skinparam linetype ortho

' Système
entity "Cueilleur" as cueilleur {
id: number (pk)
--
uid: string (50) (UNIQUE)
nom: string (50)
prenom: string (50)
commentaire: string (256) (Nullable)
date_creation: timestamp
activite_id: number (fk)
}
note left of cueilleur
    La relation [Activité - Cueilleur] change à chaque activité
    Une relation Cueilleur enregistrement permet de garder
    l'historique des cueilleurs (Pour les tags comptabilisés)
end note

entity "Activité" as activite {
id: number (pk)
--
uid: string (50) (UNIQUE)
nom: string (50) (UNIQUE)
date_creation: timestamp
date_debut: timestamp (Nullable)
date_fin: timestamp (Nullable)
}

entity "Tag" as tag {
id: number (pk)
--
uid: string (50) (UNIQUE)
etat: enum (IDLE, EN_ATTENTE, COMPTABILISE) (Nullable)
date_enregistrement: timestamp
cueilleur_id: number (fk)
}

entity "Enregistrement" as enregistrement {
    id: number (pk)
    --
    activite_id: number (fk)
    cueilleur_id: number (fk)
    tag_id: numlber (fk)
    activite_id: number (fk)
    date_affectation: timestamp
    est_conforme: boolean (Nullable)
    date_comptage: timestamp (Nullable)
}

entity "Lecteur" as lecteur {
    id: number (pk)
    --
    name: string (50) UNIQUE
    api_token: string (100) UNIQUE
    date_enregistrement: timestamp
    
}

tag }o--o| cueilleur
cueilleur ||--o{ enregistrement
activite ||--o{ enregistrement
tag ||--o{ enregistrement
cueilleur }o--o| activite
note left of tag
    La relation [Tag - Cueilleur] change à chaque activité
    Une relation Tag enregistrement permet de garder
    l'historique des affectations (Pour les tags comptabilisés)
end note

' Authentification
entity "Utilisateur" as utilisateur {
    id: number (pk)
    --
   nom: string (50)
   prenom: string (50)
   mail: string (50)
   role: ENUM(ADMIN, CHEF, OPERATEUR)
   date_creation: timestamp
}

@enduml